spring:
  application:
    name: customer-service
    
  datasource:
    url: jdbc:h2:file:~/customerbanking;DB_CLOSE_ON_EXIT=FALSE;
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
    
  h2:
    console:
      enabled: true
    
server:
  port: 6161
  
eureka:
  client:
    service-url:
      default:zone: ${EURAK_URI:http://localhost:8761/eureka}
    instance:
      prefer-ip-address: true
      
logging:
  file: customer.log
  level:
    root: 
    project:
      user:
        UserClient: FULL
