spring:
  application:
    name: api-gateway
    
server:
  port: 8080
  
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
      prefer-ip-address: true
 
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    account-service:
      path: /accounts/**
      serviceId: account-service
        
    customer-service:
      path: /customers/**
      serviceId: customer-service
  host:
    socket-timeout-millis: 30000
