spring:
  application:
    name: account-service
  
  #kafka  
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - localhost:9092
      bindings:
        notification-in:
          destination: notification
          content-type: application/json
        notification-out:
          destination: notification
          content-type: application/json
    
  datasource:
    url: jdbc:h2:file:~/accountbanking;DB_CLOSE_ON_EXIT=FALSE;
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
    
server:
  port: 6060

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      prefer-ip-address: true
      
info:
  app:
    name: account-service
    description: Account service app
    version: 0.0.1-SNAPTSHOT
    email: sbsromero@gmail.com
    phone: 00-0000
  
  managements:
    endpoints:
      web:
        exposure:
          include: '*'
    endpoint:
      metrics:
        enabled: true
